# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']
env:
  MONGO_CONNECT: 'mongodb+srv://arod90:spitfire@cluster0.oiuln.mongodb.net/VaTerra'

jobs:
  Server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Server

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          credentials: ${{ secrets.MONGO_CONNECT }}
      - run: npm ci
      - run: npm test
      - run: npm run build

  Front-end:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vaTerra

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm test
